In [35]:
import numpy as np
import matplotlib.pyplot as plt

from utils import speed

In [36]:
data = np.loadtxt('../dataset/10/1216461503656')
head, tail = data[:30], data[30:]
print(head, '\n\n', tail)

[[ 6.26147800e+01  2.97424900e+01  1.21646150e+12 -1.00000000e+00]
 [ 6.26147140e+01  2.97426650e+01  1.21646151e+12 -1.00000000e+00]
 [ 6.26146920e+01  2.97427080e+01  1.21646151e+12 -1.00000000e+00]
 [ 6.26146930e+01  2.97427640e+01  1.21646152e+12 -1.00000000e+00]
 [ 6.26147020e+01  2.97427980e+01  1.21646152e+12 -1.00000000e+00]
 [ 6.26147380e+01  2.97427710e+01  1.21646153e+12 -1.00000000e+00]
 [ 6.26147640e+01  2.97427430e+01  1.21646153e+12 -1.00000000e+00]
 [ 6.26148180e+01  2.97429130e+01  1.21646154e+12 -1.00000000e+00]
 [ 6.26148340e+01  2.97433100e+01  1.21646155e+12 -1.00000000e+00]
 [ 6.26148280e+01  2.97433610e+01  1.21646155e+12 -1.00000000e+00]
 [ 6.26148210e+01  2.97433510e+01  1.21646156e+12 -1.00000000e+00]
 [ 6.26148160e+01  2.97433420e+01  1.21646156e+12 -1.00000000e+00]
 [ 6.26148070e+01  2.97432960e+01  1.21646157e+12 -1.00000000e+00]
 [ 6.26148020e+01  2.97432750e+01  1.21646157e+12 -1.00000000e+00]
 [ 6.26148210e+01  2.97433160e+01  1.21646158e+12 -1.00000000e

In [37]:
speed.calculate_speed_in_ms(head[-2], head[-1])

0.4349271116505547