In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
data = np.loadtxt('../dataset/10/1216461503656')
head = data[:10]
print(head)

[[ 6.26147800e+01  2.97424900e+01  1.21646150e+12 -1.00000000e+00]
 [ 6.26147140e+01  2.97426650e+01  1.21646151e+12 -1.00000000e+00]
 [ 6.26146920e+01  2.97427080e+01  1.21646151e+12 -1.00000000e+00]
 [ 6.26146930e+01  2.97427640e+01  1.21646152e+12 -1.00000000e+00]
 [ 6.26147020e+01  2.97427980e+01  1.21646152e+12 -1.00000000e+00]
 [ 6.26147380e+01  2.97427710e+01  1.21646153e+12 -1.00000000e+00]
 [ 6.26147640e+01  2.97427430e+01  1.21646153e+12 -1.00000000e+00]
 [ 6.26148180e+01  2.97429130e+01  1.21646154e+12 -1.00000000e+00]
 [ 6.26148340e+01  2.97433100e+01  1.21646155e+12 -1.00000000e+00]
 [ 6.26148280e+01  2.97433610e+01  1.21646155e+12 -1.00000000e+00]]
